import '../../../features/domain/entities/over_view/over_view_entity.dart';

class PatientTourMockData {
  static Map<String, String> get demoVitals => {
    'bp': '120/80',
    'bpSystolic': '120',
    'bpDiastolic': '80',
    'pulse': '72',
    'temp': '98.4',
    'spO2': '98',
    'weight': '68',
    'height': '175',
    'lastUpdated': 'Today, 09:30 AM',
  };

  static List<PatientAppointmentEntity> get demoUpcomingAppointments => [
    PatientAppointmentEntity(
      id: 'demo_apt_1',
      doctorName: 'Dr. Rajesh Sharma',
      hospitalName: 'Apollo Speciality Hospital',
      appointmentDate: 'Today',
      rawDate: DateTime.now().toIso8601String(),
      startTime: '04:30 PM',
      duration: '30 mins',
      status: 'Confirmed',
      condition: 'Cardiac Checkup & ECG Review',
      reason: 'Routine quarterly heart rhythm follow-up',
      meetingUrl: 'https://meet.yiraclinics.com/demo-video-call',
      isTeleConsultation: true,
      patientName: 'Rahul Verma',
      patientUserId: 'demo_user_1',
    ),
    PatientAppointmentEntity(
      id: 'demo_apt_2',
      doctorName: 'Dr. Priya Nair',
      hospitalName: 'City Care Clinic',
      appointmentDate: 'Tomorrow',
      rawDate: DateTime.now().add(const Duration(days: 1)).toIso8601String(),
      startTime: '10:00 AM',
      duration: '15 mins',
      status: 'Scheduled',
      condition: 'Vitals & General Wellness',
      reason: 'Annual preventive blood test discussion',
      meetingUrl: '',
      isTeleConsultation: false,
      patientName: 'Rahul Verma',
      patientUserId: 'demo_user_1',
    ),
  ];

  static List<Map<String, dynamic>> get demoAppointmentsList => [
    {
      'id': 'demo_apt_1',
      'doctorName': 'Dr. Rajesh Sharma',
      'hospitalName': 'Apollo Speciality Hospital',
      'specialty': 'Cardiology',
      'appointmentDate': 'Today',
      'startTime': '04:30 PM',
      'status': 'Confirmed',
      'isTeleConsultation': true,
      'meetingUrl': 'https://meet.yiraclinics.com/demo-video-call',
      'reason': 'Cardiac Checkup & ECG Review',
      'patientName': 'Rahul Verma',
      'type': 'videoCall',
    },
    {
      'id': 'demo_apt_2',
      'doctorName': 'Dr. Priya Nair',
      'hospitalName': 'City Care Clinic',
      'specialty': 'General Medicine',
      'appointmentDate': 'Tomorrow',
      'startTime': '10:00 AM',
      'status': 'Scheduled',
      'isTeleConsultation': false,
      'meetingUrl': '',
      'reason': 'Annual Wellness Checkup',
      'patientName': 'Rahul Verma',
      'type': 'inPerson',
    },
    {
      'id': 'demo_apt_3',
      'doctorName': 'Dr. Amit Patel',
      'hospitalName': 'Max Healthcare',
      'specialty': 'Dermatology',
      'appointmentDate': '24 Aug 2026',
      'startTime': '02:15 PM',
      'status': 'Completed',
      'isTeleConsultation': true,
      'meetingUrl': '',
      'reason': 'Skin Allergy Consultation',
      'patientName': 'Rahul Verma',
      'type': 'videoCall',
    },
  ];
}
